name: 'release'
description: 'Release to a moon'
inputs:
  app:
    description: "App to deploy"
    required: true
  ship:
    description: "Ship to deploy to"
    required: true
  credentials:
    description: "base64-encoded GCP Service Account credentials"
    required: true
  ssh-sec-key:
    description: "A base64-encoded SSH secret key for the container to use"
    required: true
  ssh-pub-key:
    description: "The corresponding base64-encoded SSH public key"
    required: true
  ref:
    description: "The github reference to checkout when deploying"
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app }}
    - ${{ inputs.ship }}
    - ${{ inputs.credentials }}
    - ${{ inputs.ssh-sec-key }}
    - ${{ inputs.ssh-pub-key }}
    - ${{ inputs.ref }}
