name: Deploy Landscape
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Create a glob and deploy latest to ~wannec-dozzod-marzod (devstream)"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.JANEWAY_SERVICE_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Build Frontend
        working-directory: ./ui
        run: | 
          npm ci
          npm build
      - id: glob
        uses: ./.github/actions/glob
        with:
          folder: 'ui/dist/*'
          docket: 'desk/desk.docket-0'
      - name: Commit Glob
        uses: EndBug/add-and-commit@v9
        with:
          add: '-A'
          message: 'update glob: ${{ steps.glob.outputs.hash }} [skip actions]'
      - uses: ./.github/actions/release
        with:
          app: 'landscape'
          ship: 'devstream'
          credentials: ${{ secrets.JANEWAY_SERVICE_KEY }}
          ssh-sec-key: ${{ secrets.JANEWAY_SSH_SEC_KEY }}
          ssh-pub-key: ${{ secrets.JANEWAY_SSH_PUB_KEY }}