name: Deploy Landscape
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Create and deploy a glob to ~wannec-dozzod-marzod (devstream)"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          app: 'landscape'
          ship: 'devstream'
          credentials: ${{ secrets.JANEWAY_SERVICE_KEY }}
          ssh-sec-key: ${{ secrets.JANEWAY_SSH_SEC_KEY }}
          ssh-pub-key: ${{ secrets.JANEWAY_SSH_PUB_KEY }}