name: Deploy Landscape (livenet)
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: Enter the tag to deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Release to ~mister-dister-dozzod-dozzod (livenet)"
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.JANEWAY_SERVICE_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - id: deploy-prep
        name: Prep Deploy Script
        run:
          ./.github/helpers/deploy.sh tloncorp/landscape landscape mister-dister-dozzod-dozzod ${{ github.event.inputs.tag }}
      - id: 'compute-ssh'
        name: Deploy
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          project_id: mainnet
          zone: 'us-west1-b'
          user: 'urb'
          instance_name: 'wannec-dozzod-marzod'
          flags: '--verbosity=info'
          ssh_private_key: '${{ secrets.TEST_KEY }}'
          script: ${{ steps.deploy-prep.outputs.cmdfile }}